# Další operace poskytované knihovnou `clojure.core.matrix`

Nejprve použijeme dvojici příkazů `use`, které načtou všechny funkce a všechna makra ze jmenných prostorů clojure.core.matrix a clojure.core.matrix.operators:

In [1]:
(use 'clojure.core.matrix)
(use 'clojure.core.matrix.operators)

### Poznámka
po spuštění předchozí buňky se nejdříve vypíšou varování, že ve jmenném prostoru core.matrix.operators došlo k předeklarování globálních symbolů *, -, /, + a ==

## Transpozice matice

In [6]:
(def M (matrix [[1 2 3] [4 5 6] [7 8 9]]))
(pm M)
 
(transpose M)
(pm *1)

[[1.000 2.000 3.000]
 [4.000 5.000 6.000]
 [7.000 8.000 9.000]]
[[1.000 4.000 7.000]
 [2.000 5.000 8.000]
 [3.000 6.000 9.000]]


## Unární a binární operace nad maticemi

In [12]:
(def M1 (matrix [[1 2][3 4]]))
 
(def M2 (matrix [[5 6][7 8]]))
 
(pm (+ M1 M2))
(pm (- M1 M2))
(pm (* M1 M2))
(pm (* M1 100))

; zde se nejdříve vypočte inverzní matice k M1
(pm (/ M2 M1))
 
(pm (inverse M1))

(pm (inverse M2))

[[ 6.000  8.000]
 [10.000 12.000]]
[[-4.000 -4.000]
 [-4.000 -4.000]]
[[ 5.000 12.000]
 [21.000 32.000]]
[[100.000 200.000]
 [300.000 400.000]]
[[5.000 3.000]
 [2.333 2.000]]
[[-2.000  1.000]
 [ 1.500 -0.500]]
[[-4.000  3.000]
 [ 3.500 -2.500]]


## Funkce vracející informace o maticích (počet dimenzí a tvar)

In [14]:
; vektor
(def v (matrix [1 2 3 4 5 6]))
(pm v)

; 2D matice
(def M (matrix [[1 2] [3 4]]))
(pm M)

; trojrozměrná matice
(def MD (matrix [[ [1 2] [3 4] ] [ [5 6] [7 8] ] ]))
(pm MD)

[1.000 2.000 3.000 4.000 5.000 6.000]
[[1.000 2.000]
 [3.000 4.000]]
[[[1.000 2.000]
  [3.000 4.000]]
 [[5.000 6.000]
  [7.000 8.000]]]


In [15]:
(dimensionality v)

1

In [16]:
(dimensionality M)

2

In [17]:
(dimensionality MD)

3

In [18]:
(dimensionality 1)

0

In [19]:
(shape M)

[2 2]

In [20]:
(shape v)

[6]

In [21]:
(shape MD)

[2 2 2]

## Změna tvaru matice

In [22]:
(def v (matrix [1 2 3 4 5 6]))
(pm v)

[1.000 2.000 3.000 4.000 5.000 6.000]


In [23]:
; velmi užitečná funkce převzatá z APL: vektor převeden na matici
(reshape v [2 3])
(pm *1)

[[1.000 2.000 3.000]
 [4.000 5.000 6.000]]


In [25]:
; jiný tvar matice
(reshape v [3 2])
(pm *1)

[[1.000 2.000]
 [3.000 4.000]
 [5.000 6.000]]


In [27]:
(reshape v [1 6])
(pm *1)

[[1.000 2.000 3.000 4.000 5.000 6.000]]


In [28]:
(reshape v [6 1])
(pm *1)

[[1.000]
 [2.000]
 [3.000]
 [4.000]
 [5.000]
 [6.000]]


## Využití makra -> a ->> ke kompozici operací

In [29]:
; jedná se o oneliner rozepsaný kvůli větší čitelnosti na čtyři řádky
(-> (matrix (range 1 101))
    (reshape [10 10])
    transpose
    pm)

[[ 1.000 11.000 21.000 31.000 41.000 51.000 61.000 71.000 81.000  91.000]
 [ 2.000 12.000 22.000 32.000 42.000 52.000 62.000 72.000 82.000  92.000]
 [ 3.000 13.000 23.000 33.000 43.000 53.000 63.000 73.000 83.000  93.000]
 [ 4.000 14.000 24.000 34.000 44.000 54.000 64.000 74.000 84.000  94.000]
 [ 5.000 15.000 25.000 35.000 45.000 55.000 65.000 75.000 85.000  95.000]
 [ 6.000 16.000 26.000 36.000 46.000 56.000 66.000 76.000 86.000  96.000]
 [ 7.000 17.000 27.000 37.000 47.000 57.000 67.000 77.000 87.000  97.000]
 [ 8.000 18.000 28.000 38.000 48.000 58.000 68.000 78.000 88.000  98.000]
 [ 9.000 19.000 29.000 39.000 49.000 59.000 69.000 79.000 89.000  99.000]
 [10.000 20.000 30.000 40.000 50.000 60.000 70.000 80.000 90.000 100.000]]


In [30]:
; sekvence operací aplikovaných na matici M1
(-> M1
    transpose
    inverse
    (* 10000)
    transpose
    (* M2)
    (+ M1)
    pm)

[[-99999.000  60002.000]
 [105003.000 -39996.000]]
